language: R
cache: packages

r:
  - oldrel
  - release
  - devel

sudo: required

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev

before install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev libv8-dev libudunits2-dev

script:
